### ISSUE TITLE
Invert option

### ISSUE THREAD

**Issue by Sayayaya** [heisarzola/multi-channel-image#1]
It would be nice if the combiner, for each channel there was an option to invert the value for the needs of some game engines.

**Comment by heisarzola** [comment]
I'm ashamed I never saw this issue thread until now. Can't tell if I missed a notification e-mail, or if I never hooked them in the first place.

But this was a very reasonable thing to ask to add.
It's in the application now. b7bf49103abe58c25cb1ec43932626d034922554

You can download the executable release here: 
https://github.com/heisarzola/Multi-Channel-Image/releases/tag/V.1.1.0

Sorry for the long wait.

**Comment by Sayayaya** [comment]
Hey it's OK, 4 months later and I only just saw you made the change. Thank you btw, very appreciated. Using your software all the time
